export const data = [
  {
    id: 1,
    img: "JBL AZUL ALAMBRICO.jpg",
    nombreProducto: "JBL Quantum 800",
    precio: 80.5,
    cantCarrito: 1,
    color: "azul",
    modelo: "alambrico",
    marca: "JBL",
  },
  {
    id: 2,
    img: "JBL AZUL INALAMBRICO.jpg",
    nombreProducto: "Audífonos JBL T500 Pure Bass",
    precio: 50,
    cantCarrito: 1,
    color: "azul",
    modelo: "inalambrico",
    marca: "JBL",
  },
  {
    id: 3,
    img: "JBL NEGRO INALABRICO.jpg",
    nombreProducto: "Audífono JBL Bluetooth TUNE 520 Negro",
    precio: 90,
    cantCarrito: 1,
    color: "negro",
    modelo: "inalambrico",
    marca: "JBL",
  },
  {
    id: 4,
    img: "JBL ROJO INALAMBRICO.jpg",
    nombreProducto: "Audífonos inalámbricos JBL 760NC rojo",
    precio: 50,
    cantCarrito: 1,
    color: "rojo",
    modelo: "inalambrico",
    marca: "JBL",
  },
  {
    id: 5,
    img: "MSI AZUL ALAMBRICO ROJO.jpg",
    nombreProducto: "MSI Gaming Headset",
    precio: 20,
    cantCarrito: 1,
    color: "azul",
    modelo: "alambrico",
    marca: "MSI",
  },
  {
    id: 6,
    img: "MSI NEGRO ALAMBRICO Immerse Gh20.jpg",
    nombreProducto: "Auricular Gamer MSI Immerse Gh20",
    precio: 20,
    cantCarrito: 1,
    color: "negro",
    modelo: "alambrico",
    marca: "MSI",
  },
  {
    id: 7,
    img: "MSI NEGRO ALAMBRICO ROJO.jpg",
    nombreProducto: "MSI Audifono Gamer Cooler",
    precio: 20,
    cantCarrito: 1,
    color: "negro",
    modelo: "alambrico",
    marca: "MSI",
  },
  {
    id: 8,
    img: "MSI ROJO ALAMBRICO ROJO.jpg",
    nombreProducto: "Auricular Gamer MSI Ds501",
    precio: 20,
    cantCarrito: 1,
    color: "rojo",
    modelo: "alambrico",
    marca: "MSI",
  },
  {
    id: 9,
    img: "EWWTO AZUL ALAMBRICO.jpg",
    nombreProducto: "Auricular EWTTO azul alambrico",
    precio: 20,
    cantCarrito: 1,
    color: "azul",
    modelo: "alambrico",
    marca: "EWTTO",
  },
  {
    id: 10,
    img: "EWWTO NEGRO ALAMBRICO.jpg",
    nombreProducto: "Audífonos Cable Aw-x107 Negro",
    precio: 20,
    cantCarrito: 1,
    color: "negro",
    modelo: "alambrico",
    marca: "EWTTO",
  },
  {
    id: 11,
    img: "EWWTO ROJO INAMBRICO (2).jpg",
    nombreProducto: "AUDÍFONOS EWTTO ET-A4261B",
    precio: 20,
    cantCarrito: 1,
    color: "rojo",
    modelo: "inalambrico",
    marca: "EWTTO",
  },
  {
    id: 12,
    img: "EWWTO ROJO INAMBRICO.jpg",
    nombreProducto: "Audifonos Stn13 Inalambricos Wireless",
    precio: 20,
    cantCarrito: 1,
    color: "rojo",
    modelo: "inalambrico",
    marca: "EWTTO",
  },
];
